theme: jekyll-theme-cayman
title: Street Fighter II  The World Warrior
description: PROJECT 1  Development of a tribute to Street Fighter II
show_downloads: ["false"]
url: https://github.com/MarcArizaAlborni/Beat-The-Meat-Studio/wiki
baseurl: Our Wiki
